const data = {
  'Selected': 'Izabrano: {0} od {1}',
  'Uploading files': 'Slanje {0}% od {1}',
  'File size error': '{0} datoteka je prevelika, molim zadajte datoteku manju od {1}',
  'Upload failed': '{0} pogreška pri slanju',
  'Per page': '{0} Po stranici',
  'Folder': 'Mapa',
  'Login failed, please try again': 'Neuspješna prijava, pokušajte ponovo',
  'Already logged in': 'Već ste prijavljeni.',
  'Please enter username and password': 'Unesite korisničko ime i lozinku.',
  'Not Found': 'Nije pronađeno',
  'Not Allowed': 'Nije dozvoljeno',
  'Please log in': 'Prijavite se',
  'Unknown error': 'Nepoznata pogreška',
  'Add files': 'Dodaj datoteke',
  'New': 'Novi',
  'New name': 'Novo ime',
  'Username': 'Korisničko ime',
  'Password': 'Lozinka',
  'Login': 'Prijavi se',
  'Logout': 'Odjavi se',
  'Profile': 'Profil',
  'No pagination': 'Bez listanja po strani',
  'Time': 'Vrijeme',
  'Name': 'Ime',
  'Size': 'Veličina',
  'Home': 'Početna',
  'Copy': 'Kopiraj',
  'Move': 'Premjesti',
  'Rename': 'Promjeni ime',
  'Required': 'Ovo polje je obavezno',
  'Zip': 'Zip',
  'Batch Download': 'Grupno preuzimanje',
  'Unzip': 'Unzip',
  'Delete': 'Obriši',
  'Download': 'Preuzmi',
  'Copy link': 'Kopiraj link',
  'Done': 'Završeno',
  'File': 'Datoteka',
  'Drop files to upload': 'Ispusti datoteke za slanje',
  'Close': 'Zatvori',
  'Select Folder': 'Izaberi mapu',
  'Users': 'Korisnici',
  'Files': 'Datoteke',
  'Role': 'Ovlasti',
  'Cancel': 'Prekini',
  'Paused': 'Pauzirano',
  'Confirm': 'Potvrdi',
  'Create': 'Kreiraj',
  'User': 'Korisnik',
  'Admin': 'Administrator',
  'Save': 'Spremi',
  'Read': 'Čitanje',
  'Write': 'Pisanje',
  'Upload': 'Slanje',
  'Permissions': 'Prava pristupa',
  'Homedir': 'Početna mapa',
  'Leave blank for no change': 'Ostavi prazno za bez promjene',
  'Are you sure you want to do this?': 'Da li ste sigurni?',
  'Are you sure you want to allow access to everyone?': 'Da li ste sigurni da želite dozvoliti pristup svima?',
  'Are you sure you want to stop all uploads?': 'Da li ste sigurni da želite prekinuti sva slanja?',
  'Something went wrong': 'Dogodila se nepoznata pogreška',
  'Invalid directory': 'Pogrešna mapa',
  'This field is required': 'Ovo polje je obavezno',
  'Username already taken': 'Korisničko ime već postoji',
  'User not found': 'Korisnik nije pronađen',
  'Old password': 'Stara lozinka',
  'New password': 'Nova lozinka',
  'Wrong password': 'Pogrešna lozinka',
  'Updated': 'Nadopunjeno',
  'Deleted': 'Obrisano',
  'Your file is ready': 'Vaša datoteka je spremna',
  'View': 'Pogledaj',
  'Search': 'Pretraži',
  'Download permission': 'Preuzimanje',
  'Guest': 'Gost',
}

export default data

